Handling properly datetime fields
kalwalkden/django-materializecss-form pull request #27
Opened 2018-12-03 22:44 UTC by carllopez

2018-12-04 18:27 UTC, kalwalkden requested changes

2018-12-04 18:27 UTC, kalwalkden commented on materializecssform/templates/materializecssform/field.html
> +    <div class="input-field col {{ classes.label }} {{ classes.value }} {{ classes.single_value }}">
Please describe how to use the datetime-local class in the readme

2018-12-04 18:28 UTC, kalwalkden commented
@carllopez could you include a screenshot of what this looks like?

2018-12-10 21:36 UTC, carllopez commented on materializecssform/templates/materializecssform/field.html
> +    <div class="input-field col {{ classes.label }} {{ classes.value }} {{ classes.single_value }}">
Readme has been updated

2018-12-10 21:38 UTC, kalwalkden approved these changes

2018-12-10 21:38 UTC, kalwalkden commented on materializecssform/templates/materializecssform/field.html
> +        <input type="date" id="{{ field.auto_id }}" name="{{ field.html_name }}" value="{% if field.value %}{{ field.value }}{% endif %}" {% include 'materializecssform/attrs.html' %} >
Why remove ```class="datepicker"```? The datetime works as is.

2018-12-10 21:38 UTC, merged

2018-12-10 21:40 UTC, carllopez commented
@kalwalkden here you go:

![datetimefield](https://user-images.githubusercontent.com/556361/49763336-f541fc80-fc91-11e8-836c-dd735089f9a6.jpg)